function fileInfo(hfig,evnt) %#ok

gd=guidata(hfig);

fields={'Filename';...
    'Date Collected';...
    'Time Start';...
    'Time End';...
    'Transducer Type';...
    'Transducer Frequency';...
    'Samples per Ping';...
    'Ping Interval';...
    'Blanking Distance';...
    'Data Threshold';...
    'Digitize Frequency';...
    'Temperature';...
    'Salinity';...
    'Sound Velocity'};

units={[];...
    'YYYY/MM/DD';...
    'hh:mm:ss';...
    'hh:mm:ss';...
    [];...
    'kHz';...
    [];...
    'Hz';...
    'm';...
    'dB';...
    'Hz';...
    'deg C';...
    'psu';...
    'm/s'};

start=find(isfinite(gd.raw.mtime),1,'first');
endi=find(isfinite(gd.raw.mtime),1,'last');

data=cell(length(fields),1);
data{1}=gd.opt.filename;
data{2}=datestr(gd.raw.mtime(start),26);
data{3}=datestr(gd.raw.mtime(start),13);
data{4}=datestr(gd.raw.mtime(endi),13);
data{5}=gd.raw.snd.rxee.transducerType;
data{6}=sprintf('%d',...
    gd.raw.snd.rxee.frequency/1000);
data{7}=sprintf('%d',...
    gd.raw.snd.sampperping);
data{8}=sprintf('%0.1f',...
    1/gd.raw.snd.pingperiod);
data{9}=sprintf('%0.1f',...
    gd.raw.snd.blank);
data{10}=sprintf('%0.1f',...
    gd.raw.snd.threshold);
data{11}=sprintf('%d',...
    gd.raw.snd.rxee.sampleRate);
data{12}=sprintf('%0.1f',...
    gd.raw.env.temperature);
data{13}=sprintf('%0.1f',...
    gd.raw.env.salinity);
data{14}=sprintf('%0.1f',...
    gd.raw.env.sv);

tabledata=cat(2,fields,data,units);    

h2=figure;
set(h2,'Name','File Info','menubar','none','numbertitle','off');
mtable=uitable(h2,'Data',tabledata,'columnname',{'Property','Value','units'});
set(mtable,'units','normalized','position',[0.1 0.1 0.8 0.75]);

pix=get(h2,'position');
cwidth=floor([0.25 0.325 0.15]*pix(3));
set(mtable,'columnwidth',num2cell(cwidth))