function ppk=readgnav(fname)

fid=fopen(fname,'r');


hdrs=textscan(fgetl(fid),'%s',...
    'delimiter',',');

fmt=['%s%s',repmat('%f',1,10)];
data = textscan(fid,fmt,'delimiter',',');
obs=cell2struct(data',hdrs{1});
fclose(fid);

obs.mtime=datenum(strcat(cellfun(@(x)([x,' ']),obs.Date,'un',0),obs.Time),...
    'mm/dd/yyyy HH:MM:SS.FFF');

%transform the relavant parameters
ofields={'mtime';...
    'Latitude';...
    'Longitude';...
    'Quality';...
    'Num_Sat';...
    'Comb_RMS';...
    'PDOP';...
    'Ellip_Height';...
    'Ortho_height';...
    'Easting';...
    'Northing'};
nfields={'mtime',;...
    'lat';...
    'lon';...
    'mode';...
    'nsats';...
    'rms';...
    'hdop';...
    'ellipsoid_ht';...
    'elev';...
    'x';...
    'y'};
for i=1:length(ofields)
    ppk.(nfields{i})=obs.(ofields{i});
end

ppk.geoid=obs.Ellip_Height-obs.Ortho_height;