function showKeys(hfig,evnt) %#ok

str={'The following is a list of keyboard shortcuts:';...
    ' ';...
    'e:  lasso tool';...
    'u:  undo last edit';...
    'z:  zoom box';...
    'f:  show full extents';...
    'l:  local filter';...
    'o:  open new file';...
    'd:  hand digitize';...
    'CR: refresh classification'};

h=helpdlg(str,'Keyboard Shortcuts');
g=get(h,'children');
set(g(1:2),'fontsize',18)