function writeini(hfig,evnt) %#ok

gd=guidata(hfig);

[filename, pathname] = uiputfile( ...
    {'*.ini', 'INI Files'}, ...
    'Save as',[gd.opt.outpath,'*.ini']);

if filename==0
    return
else
    gd.opt.outpath=pathname;
end

names=fieldnames(gd.opt);
params={'filename','%s';...
    'pathname','%s';...
    'outpath','%s';...
    'avgint','%f';...
    'blanking','%f';...
    'smoothing','%f';...
    'channel','%f';...
    'gpsOffset','%f';...
    'maxdepth','%f';...
    'mindepth','%f';...
    'quantity','%s',;...
    'sal','%f';...
    'temp','%f',;...
    'threshold','%f';...
    'vegHeight','%f'};

fid=fopen([gd.opt.outpath,filename],'wt');

for i=1:length(params);
      ind=find(strcmpi(params(i,1),names), 1);
      
        if ~isempty(ind)
            fprintf(fid,'%-13s= ',params{i,1});
            fprintf(fid,[params{i,2},'\n'],gd.opt.(names{ind}));
        end
end
fclose(fid);
guidata(hfig,gd);